### ISSUE TITLE
lessons from other ndbc packages

### ISSUE THREAD

**Issue by raybellwaves** [wavebitscientific/ndbc#2]
Not an issue. Discussion.

Searched for ndbc to find this repo and found others (a lot). May be able to learn some things if you weren't aware.

https://github.com/nickc1/buoypy
https://github.com/erewok/noaa-data (5 years old though)
https://github.com/supermanzer/NDBC
https://github.com/jrleeman/ndbc_interactive
https://github.com/calebvandenberg/py-ndbc-buoy-spectra

**Comment by tiagofassoni** [comment]
Hey, thanks for the round-up on packages

**Comment by milancurcic** [comment]
If you have any specific ideas for any of the features that should be part of this repo, please open an issue.
